- src/endpoints/automations.yaml
- src/endpoints/namespace.yaml
- src/endpoints/project_secrets.yaml
- src/main.yaml
- src/schemas/namespace.yaml
- src/schemas/project_secret.yaml
This PR describes the endpoints for creating Sentry projects and retrieving project secrets.  The latter is not used in imbi-ui but is useful when configuring applications outside of Imbi.
> Sentry integration

- src/schemas/project_type.yaml
This commit updates the openapi spec to allow null values for gitlab_project_prefix, which matches our Postgres schema. This also helps maintain the philosophy that Imbi should be capable of integrating with other tools and platforms
> Allow null gitlab_project_prefix

- src/components/requests.yaml
- src/components/schemas.yaml
- src/endpoints/cookie_cutter.yaml
- src/endpoints/environment.yaml
- src/endpoints/group.yaml
- src/endpoints/namespace.yaml
- src/endpoints/operations_log.yaml
- src/endpoints/project_fact_type.yaml
- src/endpoints/project_fact_type_enum.yaml
- src/endpoints/project_fact_type_range.yaml
- src/endpoints/project_link_type.yaml
- src/endpoints/project_links.yaml
- src/endpoints/project_type.yaml
- src/endpoints/project_urls.yaml
- src/endpoints/projects.yaml
The schema for a JSON patch request was not valid according to the OpenAPI spec.  Specifically, an `array` is required to have an `items` clause.  You can make this work with a recursive `$ref`.  I also moved the JSON Patch request into a reusable component (in _components/requests.yaml_) since we were repeating it in a lot of places.
> Fix recursive type

- src/components/requests.yaml
- src/components/schemas.yaml
- src/endpoints/project_notes.yaml
- src/schemas/project_note.yaml
The `project_id` field is required to be in the responses for the CRUD framework to work properly.  I bundled some changes to the JSON patch example as well.  I can make b9c0017 a separate PR if desired.
> Add project-id to project notes

- src/endpoints/activity_feed.yaml
- src/endpoints/operations_log.yaml
- src/endpoints/project_activity_feed.yaml
- src/schemas/operations_log.yaml
This PR adds a new property to the project update feed and ops log entries so that they can have separate data models.  See https://github.com/AWeber-Imbi/imbi-ui/issues/30, https://github.com/AWeber-Imbi/imbi-ui/issues/31, and https://github.com/AWeber-Imbi/imbi-api/pull/30 for related PRs.
> Add feed entry type

- src/endpoints/project_facts.yaml
- src/endpoints/projects.yaml
The response from GET /projects is an object with two fields: `data` and `rows`, not just an array.
> Fix GET /projects response docs

- src/components/schemas.yaml
Note that we need to specify `nullable=true` twice for it to cover all of the cases -- the root property allows the overall value to be null and we need exactly one nullable path through the `oneOf` as well.
This will address https://github.com/AWeber-Imbi/imbi-api/issues/40 after the openapi.yaml is updated there as well.
> Make 'null' a valid value in a patch document

- src/endpoints/integrations.yaml
- src/endpoints/project_identifiers.yaml
- src/main.yaml
- src/schemas/integration.yaml
This PR adds `/projects/{id}/identifiers`, `/projects/{id}/identifiers/{name}` endpoints for managing surrogate identifiers for projects. I also reworked the `/integrations` and `/integrations/{id}` endpoints to refer to new data structures. The current endpoints are not used so it is safe to repurpose them. The new data model exposes the tables introduced in [imbi-schema#16](https://github.com/AWeber-Imbi/imbi-schema/pull/16/files).
> Add surrogate project identifiers

- src/endpoints/automations.yaml
- src/endpoints/integration_notifications.yaml
- src/endpoints/notification_filters.yaml
- src/endpoints/notification_rules.yaml
- src/endpoints/project_identifiers.yaml
- src/main.yaml
- src/schemas/automations.yaml
This PR adds the endpoint specifications for the new endpoints that populate the entities from https://github.com/AWeber-Imbi/imbi-schema/pull/19. The endpoints are more complex than our more-anemic CRUD endpoints. Instead of introducing a CRUD endpoint for an _Automation_ and accessory endpoints for associating the Automation with project types and dependent automations, I switched to using a complex document with nested identifiers.
<details>
<summary>Example of dependent automations</summary>
Both automations are implemented by the same integration. The second automation (`gitlab-first-commit`) requires that the first on (`gitlab-create-project`) will be run as well.
```json
[
{
"id": 1,
"name": "Create project",
"slug": "gitlab-create-project",
"integration_name": "gitlab", …
```
> Automation CRUD endpoints

- src/endpoints/namespace.yaml
- src/endpoints/project_configuration_ssm.yaml
- src/endpoints/projects.yaml
- src/main.yaml
- src/schemas/namespace.yaml
- src/schemas/project.yaml
- src/schemas/project_configuration_ssm.yaml
This adds a new endpoint to fetch AWS SSM parameters for a given project.
It also adds an optional `aws_ssm_slug` to the namespace schema so that administrators can specify a custom version of the namespace for the SSM parameter path prefix (such as lowercasing the slug value...)
> Endpoint for SSM config and aws_ssm_slug to namespace endpoint

- src/endpoints/component_usage_report.yaml
- src/main.yaml
This describes the Component Usage report that is implemented in https://github.com/AWeber-Imbi/imbi-api/pull/91. As usual, the built OpenAPI spec is included in that PR.
> Add GET /reports/component-usage

- package.json
- src/schemas/project_link.yaml
The OpenAPI validator that we are currently using rejects the long URLs for linking to logs in our backend provider.
> Remove uri format from project link URLs

- src/endpoints/project_configuration_ssm.yaml
- src/main.yaml
- src/schemas/project_configuration_ssm.yaml
This updates the GET and POST endpoints to use the updated SSM schema with an object with environment keys, and then a nested object with the type and value.
The PATCH endpoint expects JSON-patch to update the type and/or values of params, in addition to deleting or adding new ones.
> Use updated SSM schema & add PATCH endpoint

- src/endpoints/project_dependencies.yaml
- src/schemas/project_dependency.yaml
This adds an optional query string parameter `includes` for requesters to specify they want expanded project information about the dependencies.
> Add optional project info in dependency endpoint

- src/endpoints/project_dependencies.yaml
- src/schemas/automations.yaml
- src/schemas/project_dependency.yaml
This adds optional `automations` fields to the request payload for the POST and DELETE endpoints of project dependencies. It specifies the two new automation types `create-project-dependency` and `remove-project-dependency`. It also adds missing `created_at` in the GET endpoint.
> Add automations to project dependencies

- src/endpoints/project_components.yaml
I pivoted away from a per-component numeric score to a status based on the component's active version and the project's version of the component.
Corresponds to specification in https://github.com/AWeber-Imbi/imbi-api/pull/107
> Update /projects/{id}/components response

- src/endpoints/project_components.yaml
The API was returning this *instead of* version 🙁
> Add active_version to /projects/{id}/components

- src/schemas/operations_log.yaml
This doesn't change the backend storage; however, the UI will be updated to allow for commas (and spaces) during editing with the spaces being removed before saving.
I also added `recorded_at` to the list of required properties since the API fails without it (https://github.com/AWeber-Imbi/imbi/issues/91).
> Permit comma-separation in Ops Log ticket slugs

- src/schemas/operations_log.yaml
This field tracks *when* the event occurred at as opposed to when it was added to the system. The recorded at field tracks when it was added.
I also removed the ability to set recorded_at and recorded_by since they are set automatically by the API. We specifically DO NOT want the user to be able to set these.
> Add Operations Log occurred_at

- src/endpoints/operations_log.yaml
- src/schemas/operations_log.yaml
This is an optional override of `recorded_by` for display purposes. If it is included in the `POST /operations-log` request, then it will be returned from `GET /operations-log/{id}`. Otherwise, `performed_by` will be `null` in the various read operations.
> Add OperationsLog.performed_by

- src/endpoints/operations_log.yaml
- src/endpoints/projects.yaml
This PR adds an optional `id` parameter to the `/operations-log/build-search-index` and `/projects/build-search-index` endpoints. If the parameter is not present, then it uses the current behavior. If it is specified, then only the specified ID (or IDs) will be reindexed.
> Add id params to opensearch index endpoints
